// Generated by build_bundles.py — do not edit.
export const BUNDLE_STATS: { slug: string; pages: number; sizeKb: number }[] = [
  { slug: 'complete-pack', pages: 283, sizeKb: 1815 },
  { slug: 'starter-pack', pages: 74, sizeKb: 514 },
];
