// GENERATED FILE — do not edit by hand.
// Source: guides/content/*.md front-matter.
// Regenerate with: python3 guides/build_catalogue.py

import type { Guide } from './guides';

export const GENERATED_GUIDES: Guide[] = [
  { slug: 'agentic-economy', title: 'WTF is the Agentic Economy', description: 'The big picture. What actually happened in 2026, who the players are, what is real and what is hype. Start here.', hook: 'AI stopped answering questions. *It started doing jobs.*', bestFor: 'Best for: first read', capability: 'The 2026 story', price: 7, stripePriceId: 'price_1UGyCKBaLipfLqFsQRvInJDx', badge: '🌍 Start here', featured: true, category: 'foundation', file: 'wtf-is-the-agentic-economy.pdf', starter: true },
  { slug: 'ai-agent', title: 'WTF is an AI Agent', description: 'What an agent actually is, how it thinks, the main types, real examples, and the risks. The foundation for everything else in the series.', hook: 'Not a chatbot. *A colleague that works while you sleep.*', bestFor: 'Best for: total beginners', capability: 'How agents think', price: 7, stripePriceId: 'price_1UGyCLBaLipfLqFsqNaxMEfi', badge: null, featured: false, category: 'foundation', file: 'wtf-is-an-ai-agent.pdf', starter: true },
  { slug: 'api', title: 'WTF is an API', description: 'The thing connecting everything in the agentic economy — explained simply, finally.', hook: 'The plumbing that connects *everything in the agentic economy.*', bestFor: 'Best for: business owners', capability: 'MCP explained', price: 7, stripePriceId: 'price_1UGyCMBaLipfLqFsAEy5Ngzj', badge: null, featured: false, category: 'foundation', file: 'wtf-is-an-api.pdf', starter: false },
  { slug: 'llm', title: 'WTF is an LLM', description: 'Large language models are the engine behind every AI company. Here\'s how they actually work.', hook: 'The brain inside every agent, *without a single equation.*', bestFor: 'Best for: curious non-techies', capability: 'Who makes what', price: 7, stripePriceId: 'price_1UGyCNBaLipfLqFsl4pBwqcn', badge: null, featured: false, category: 'foundation', file: 'wtf-is-an-llm.pdf', starter: true },
  { slug: 'polsia', title: 'WTF is Polsia', description: 'The one-person startup that raised $30M to let AI run your company. What is real, what it costs, and who it is actually for.', hook: 'Half a million AI-run companies. *One in ten earned a dollar.*', bestFor: 'Best for: before you subscribe', capability: 'Real fees, real numbers', price: 7, stripePriceId: 'price_1UGyCOBaLipfLqFsvHnjwiZJ', badge: '🔥 Most popular', featured: true, category: 'platforms', file: 'wtf-is-polsia.pdf', starter: false, relatedTool: 'polsia' },
  { slug: 'openclaw', title: 'WTF is OpenClaw', description: 'The open-source personal agent with millions of users. The wild origin story, the security warnings, and where it stands now.', hook: 'From one developer\'s side project to *three million users.*', bestFor: 'Best for: your own agent', capability: 'The full story', price: 7, stripePriceId: 'price_1UGyCPBaLipfLqFsine4MnUH', badge: null, featured: false, category: 'personal', file: 'wtf-is-openclaw.pdf', starter: false, relatedTool: 'openclaw' },
  { slug: 'paperclip', title: 'WTF is Paperclip', description: 'The open-source app for managing a team of AI agents like a company: org chart, budgets, approvals. What it is, what it is not, and who should run it.', hook: 'An org chart for AI agents *you own and run yourself.*', bestFor: 'Best for: running 2+ agents', capability: 'Open-source', price: 7, stripePriceId: 'price_1UGyCQBaLipfLqFs6YQYfl0w', badge: '🧑‍💼 Agent teams', featured: false, category: 'platforms', file: 'wtf-is-paperclip.pdf', starter: false },
  { slug: 'anthropic', title: 'WTF is Anthropic', description: 'The company behind Claude. Founding story, the safety mission, the trillion-dollar valuation, and why its model powers so much of the agentic economy.', hook: 'Founded on safety. *Now worth nearly a trillion dollars.*', bestFor: 'Best for: understanding the lab', capability: 'Fable and Mythos', price: 7, stripePriceId: 'price_1UGyCRBaLipfLqFsb0WEbc0t', badge: null, featured: false, category: 'claude', file: 'wtf-is-anthropic.pdf', starter: false },
  { slug: 'claude', title: 'WTF is Claude', description: 'Anthropic\'s AI model. The family, the new Fable and Mythos tier, what it can do, and why it powers so many agents — including rivals\' products.', hook: 'The model *most of the agentic economy chose.*', bestFor: 'Best for: choosing a tier', capability: 'Why agents run on it', price: 7, stripePriceId: 'price_1UGyCSBaLipfLqFsxPelJGfX', badge: null, featured: false, category: 'claude', file: 'wtf-is-claude.pdf', starter: true },
  { slug: 'claude-code', title: 'WTF is Claude Code', description: 'The autonomous developer that changed Anthropic\'s trajectory. How it works, how it compares, and how non-developers are using it now.', hook: 'The autonomous developer, *now for non-developers too.*', bestFor: 'Best for: building without code', capability: 'vs Codex, Devin, Cursor', price: 7, stripePriceId: 'price_1UGyCTBaLipfLqFsK5Q9s3ry', badge: null, featured: false, category: 'claude', file: 'wtf-is-claude-code.pdf', starter: false },
  { slug: 'cowork', title: 'WTF is Cowork', description: 'Claude Code was for developers. Cowork is for everyone else. What it does, what it costs, and how it changed the work-agent market.', hook: 'Claude Code was for developers. *Cowork is for everyone else.*', bestFor: 'Best for: delegating real work', capability: 'On your $20 plan', price: 7, stripePriceId: 'price_1UGyCUBaLipfLqFs0nW7xDYT', badge: null, featured: false, category: 'claude', file: 'wtf-is-cowork.pdf', starter: false },
  { slug: 'hire-agent', title: 'How to Hire an AI Agent for Your Business', description: 'The practical guide. Pick the task, pick the agent, write the brief, start read-only, measure honestly. No code, no prior AI experience.', hook: 'Pick the task, write the brief, *start read-only.*', bestFor: 'Best for: small businesses', capability: 'Step by step', price: 7, stripePriceId: 'price_1UGyCVBaLipfLqFswpjYKh4L', badge: '💼 Practical', featured: false, category: 'practical', file: 'how-to-hire-an-ai-agent.pdf', starter: true },
  { slug: 'whos-who', title: 'Who\'s Who in the Agentic Economy', description: 'The map. Every lab, agent, platform and piece of infrastructure that matters, one line each, sorted by layer. Read this first, then go deep.', hook: 'Forty-five names, seven layers, *one line each.*', bestFor: 'Best for: the whole picture', capability: 'Read this first', price: 7, stripePriceId: 'price_1UGyCWBaLipfLqFsguDQttTJ', badge: '🗺️ The map', featured: true, category: 'map', file: 'whos-who-in-the-agentic-economy.pdf', starter: true },
  { slug: 'which-ai', title: 'Which AI Should I Actually Use?', description: 'Claude vs ChatGPT vs Gemini vs Muse vs Grok vs DeepSeek, for a normal person. Which to use for what, what each costs, and the catches.', hook: 'Six model families, one leaderboard. *Here is which to actually use.*', bestFor: 'Best for: picking a plan', capability: 'Prices and catches', price: 7, stripePriceId: 'price_1UGyCXBaLipfLqFsMODi6aKs', badge: '🧭 Decision guide', featured: true, category: 'map', file: 'which-ai-should-i-actually-use.pdf', starter: true },
  { slug: 'meta-muse', title: 'WTF is Meta Muse', description: 'Meta\'s free personal agent in WhatsApp. What it does, the security design, the pricing, and the trust question nobody puts in the demo.', hook: 'Meta\'s agent lives in WhatsApp *and pays with its own card.*', bestFor: 'Best for: life admin', capability: 'Trust questions answered', price: 7, stripePriceId: 'price_1UGyCYBaLipfLqFshYJ1S4Jw', badge: '🆕 New', featured: true, category: 'personal', file: 'wtf-is-meta-muse.pdf', starter: false },
  { slug: 'grok-bot', title: 'WTF is Grok Bot', description: 'Elon Musk\'s work agent: a team of bots with their own cloud computer and your real logins, coordinated by a Chief of Staff. What it does, costs and risks.', hook: 'A team of named bots *with your real logins.*', bestFor: 'Best for: delegating a function', capability: 'Risks laid out', price: 7, stripePriceId: 'price_1UGyCZBaLipfLqFsj6hkAD68', badge: '🆕 New', featured: false, category: 'work', file: 'wtf-is-grok-bot.pdf', starter: false },
  { slug: 'chatgpt-work', title: 'WTF is ChatGPT Work', description: 'OpenAI\'s work agent, inside ChatGPT. Give it an outcome, get finished files back. What it does, what it costs on your plan, and the catches.', hook: 'Give it an outcome. *Get the finished deck back.*', bestFor: 'Best for: ChatGPT users', capability: 'vs Cowork', price: 7, stripePriceId: 'price_1UGyCaBaLipfLqFsAcLZ3SMR', badge: null, featured: false, category: 'work', file: 'wtf-is-chatgpt-work.pdf', starter: false },
  { slug: 'china-ai', title: 'WTF is Happening with China\'s AI', description: 'DeepSeek, Qwen, Kimi, GLM and the open-weight strategy. Who the Chinese labs are, why they give models away, and what it means for anyone running agents.', hook: 'The best models you can download *are Chinese.*', bestFor: 'Best for: builders on a budget', capability: 'Open weights explained', price: 7, stripePriceId: 'price_1UGyCcBaLipfLqFstcYqKVZu', badge: '🇨🇳 Map', featured: false, category: 'map', file: 'wtf-is-happening-with-chinas-ai.pdf', starter: false },
  { slug: 'nanocorp', title: 'WTF is NanoCorp', description: 'The Polsia rival built by AI researchers that publishes its companies\' real revenue. How it works, what it costs, and what the live numbers say.', hook: 'The only platform that *publishes what its companies earn.*', bestFor: 'Best for: fast experiments', capability: 'Polsia alternative', price: 7, stripePriceId: 'price_1UGyCcBaLipfLqFsBDesM6a9', badge: null, featured: false, category: 'platforms', file: 'wtf-is-nanocorp.pdf', starter: false },
  { slug: 'codex', title: 'WTF is Codex', description: 'OpenAI\'s coding agent, now a tab in ChatGPT. What it does, how it compares with Claude Code, what it costs on each plan, and the catches.', hook: 'OpenAI\'s coding agent, *one tab away in ChatGPT.*', bestFor: 'Best for: parallel tasks', capability: 'vs Claude Code', price: 7, stripePriceId: 'price_1UGyCdBaLipfLqFsSTBFQgV0', badge: null, featured: false, category: 'work', file: 'wtf-is-codex.pdf', starter: false },
  { slug: 'picks-and-shovels', title: 'The Picks and Shovels', description: 'The infrastructure layer: Nvidia, the clouds, Hugging Face, GitHub, Stripe, power. Who gets paid whichever agent wins, and why it matters to you.', hook: 'Whoever wins the agent race, *these companies get paid.*', bestFor: 'Best for: investors and builders', capability: 'The bubble question', price: 7, stripePriceId: 'price_1UGyCeBaLipfLqFsmkiCcK7R', badge: '⛏️ Map', featured: false, category: 'map', file: 'the-picks-and-shovels.pdf', starter: false },
  { slug: 'launch-weekend', title: 'Launch an AI-Run Company in a Weekend', description: 'The practical playbook: validate an idea on Saturday, launch it on Polsia, NanoCorp or Paperclip on Sunday, and know by Friday whether it sells.', hook: 'Validate on Saturday. *Launch on Sunday.*', bestFor: 'Best for: first-time founders', capability: 'Two-day plan', price: 7, stripePriceId: 'price_1UGyCfBaLipfLqFsXrR9gQtQ', badge: '🚀 Practical', featured: true, category: 'practical', file: 'launch-an-ai-run-company-in-a-weekend.pdf', starter: true },
  { slug: 'solo-stack', title: 'The Solo Founder\'s AI Stack', description: 'Beyond agents: the voice, video, image, deck, research and automation tools a one-person business runs on. Seven seats, real prices, what to buy first.', hook: 'Seven seats a one-person business *fills with software.*', bestFor: 'Best for: solo operators', capability: 'Real prices', price: 7, stripePriceId: 'price_1UGyCgBaLipfLqFsR6W07wHi', badge: null, featured: false, category: 'practical', file: 'the-solo-founders-ai-stack.pdf', starter: false },
];

import type { Bundle } from './guides';

/** Bundle copy and prices. Membership is derived in guides.ts. */
export const GENERATED_BUNDLES: Omit<Bundle, 'includes'>[] = [
  { slug: 'starter-pack', title: 'The Agentic Economy Starter Pack', description: 'The eight guides that take you from "WTF is going on" to launching your first AI-run company.', price: 29, file: 'agentic-economy-starter-pack.pdf' },
  { slug: 'complete-pack', title: 'The Complete WTF Agents Pack', description: 'Everything. The full picture of the agentic economy, the platforms, the AI, and how to use it.', price: 49, file: 'complete-wtf-agents-pack.pdf' },
];
