#!/usr/bin/env python3
"""Write lib/guide-dates.generated.ts: when each guide last changed.

The sitemap used to read this from git at build time, which works locally and
silently does not on Vercel: the deploy is a shallow clone, `git log` finds no
commit for most files, and every one of them falls back to the build time — the
same "everything changed at once" signal the per-URL lastmod exists to avoid.

So the dates are resolved here, where the full history is, and committed like
the catalogue. Run by regenerate_all_guides.py, which already runs on every
content change, so the two cannot drift.
"""
import os
import subprocess
import sys
from datetime import datetime, timezone

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(BASE, 'guides', 'content')

# Non-guide routes and the sources that decide when they changed.
ROUTE_SOURCES = {
    'home': ['app/page.tsx', 'lib/guides.generated.ts'],
    'companies': ['lib/companies.ts', 'app/companies/page.tsx'],
    'tools': ['lib/tools.ts', 'app/tools/page.tsx'],
    'bundles': ['guides/bundles.py', 'lib/guides.generated.ts'],
}


def git_date(paths, reverse=False):
    args = ['git', 'log', '--reverse' if reverse else '-1', '--format=%cI', '--', *paths]
    try:
        out = subprocess.run(args, cwd=BASE, capture_output=True, text=True).stdout.strip()
    except OSError:
        return None
    lines = [l for l in out.split('\n') if l]
    return lines[0] if lines else None


def mtime(path):
    """For a guide added but not yet committed, the file's own timestamp."""
    ts = os.path.getmtime(os.path.join(BASE, path))
    return datetime.fromtimestamp(ts, tz=timezone.utc).isoformat()


def slug_of(path):
    with open(os.path.join(BASE, path), encoding='utf-8') as fh:
        for line in fh:
            if line.startswith('slug:'):
                return line.split("'")[1]
    return None


def main():
    rows = []
    for name in sorted(os.listdir(CONTENT)):
        if not name.endswith('.md'):
            continue
        rel = f'guides/content/{name}'
        slug = slug_of(rel)
        if not slug:
            sys.exit(f'ERROR: {rel} has no slug')
        modified = git_date([rel]) or mtime(rel)
        published = git_date([rel], reverse=True) or modified
        rows.append(f"  {{ slug: '{slug}', published: '{published}', modified: '{modified}' }}")

    routes = []
    for key, paths in ROUTE_SOURCES.items():
        existing = [p for p in paths if os.path.exists(os.path.join(BASE, p))]
        d = git_date(existing) if existing else None
        d = d or (mtime(existing[0]) if existing else datetime.now(timezone.utc).isoformat())
        routes.append(f"  {key}: '{d}'")

    out = os.path.join(BASE, 'lib', 'guide-dates.generated.ts')
    with open(out, 'w') as fh:
        fh.write(
            '// Generated by guides/build_dates.py — do not edit.\n'
            '//\n'
            '// Resolved from git here rather than at build time: the Vercel deploy is a\n'
            '// shallow clone and cannot see most of the history.\n'
            'export const GUIDE_DATES: { slug: string; published: string; modified: string }[] = [\n'
            + ',\n'.join(rows) + ',\n];\n\n'
            'export const ROUTE_DATES: Record<string, string> = {\n'
            + ',\n'.join(routes) + ',\n};\n'
        )
    print(f'wrote lib/guide-dates.generated.ts — {len(rows)} guides, {len(routes)} routes')


if __name__ == '__main__':
    main()
