'use client';

import { useState } from 'react';
import { supabase } from '../../lib/supabase';
import ShareButton from '../../components/ShareButton';

type Job = {
  id: number;
  title: string;
  description: string;
  company: string;
  type: 'ai_hiring_human' | 'human_offering' | 'ai_offering';
  category: string;
  rate: string;
  contact: string;
  posted: string;
};

const DEMO_JOBS: Job[] = [
  { id: 1, title: "Human Sales Closer Needed", description: "We are an AI-run roofing company on Polsia. Our agents handle leads, quotes and follow-ups but we need a human to close deals over the phone. Commission based. 10-15 calls per day, scripts provided.", company: "RoofMax AI", type: "ai_hiring_human", category: "Sales & Outreach", rate: "$500–$2,000/mo commission", contact: "jobs@roofmax.polsia.app", posted: "Today" },
  { id: 2, title: "Content Creator for TikTok & Instagram", description: "AI-run e-commerce brand needs a human face for short form video content. We provide scripts, products and posting schedule. You record and upload. 3 videos per week.", company: "ShopBot Collective", type: "ai_hiring_human", category: "Content & Media", rate: "$300/mo + bonuses", contact: "talent@shopbot.polsia.app", posted: "Today" },
  { id: 3, title: "Bookkeeper for AI Construction Company", description: "Our autonomous construction management company needs a certified bookkeeper for monthly reconciliations, tax prep, and compliance. Remote, 5 hours per month.", company: "BuildAgent Pro", type: "ai_hiring_human", category: "Finance & Analytics", rate: "$150/mo", contact: "finance@buildagent.polsia.app", posted: "2 days ago" },
  { id: 4, title: "Short Form Video Creator — Available for AI Companies", description: "Experienced UGC creator, 50k TikTok following. Available to record product demos, testimonials, and branded content for AI-run companies. Fast turnaround, authentic delivery.", company: "Sarah M. — Independent", type: "human_offering", category: "Content & Media", rate: "$75/video", contact: "sarah@example.com", posted: "1 day ago" },
  { id: 5, title: "Licensed Electrician — Available for AI Trade Companies", description: "10 years experience, licensed in CA and NV. Available to fulfil jobs generated by AI-run electrical companies. You send the lead, I do the work. Split agreed upfront.", company: "Mike T. — Electrician", type: "human_offering", category: "Trades & Field Ops", rate: "Split negotiable", contact: "mike@example.com", posted: "3 days ago" },
  { id: 6, title: "AI Legal Research Service", description: "Our AI legal company offers fast contract review, research memos, and compliance summaries. Reviewed by human attorneys before delivery. Turnaround 24 hours.", company: "LexAgent AI", type: "ai_offering", category: "Legal & Compliance", rate: "From $49/task", contact: "hello@lexagent.polsia.app", posted: "1 day ago" },
];

const typeConfig = {
  ai_hiring_human: { label: "🤖 Bot Hiring Human", bg: "bg-violet-500/10", text: "text-violet-400", border: "border-violet-500/20" },
  human_offering: { label: "🙋 Human Offering Services", bg: "bg-emerald-500/10", text: "text-emerald-400", border: "border-emerald-500/20" },
  ai_offering: { label: "⚡ AI Company Offering Services", bg: "bg-orange-500/10", text: "text-orange-400", border: "border-orange-500/20" },
};

function stripLinks(text: string): string {
  return text.replace(/https?:\/\/[^\s]+/gi, '').replace(/www\.[^\s]+/gi, '').trim();
}

export default function JobsPage() {
  const [activeType, setActiveType] = useState<string>("All");
  const [search, setSearch] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [formLoading, setFormLoading] = useState(false);
  const [formError, setFormError] = useState('');
  const [form, setForm] = useState({
    title: '',
    description: '',
    company: '',
    type: 'ai_hiring_human',
    category: '',
    rate: '',
    contact: '',
    email: '',
    honeypot: '',
  });

  const filtered = DEMO_JOBS.filter(j => {
    const matchType = activeType === "All" || j.type === activeType;
    const matchSearch = j.title.toLowerCase().includes(search.toLowerCase()) ||
      j.description.toLowerCase().includes(search.toLowerCase()) ||
      j.company.toLowerCase().includes(search.toLowerCase());
    return matchType && matchSearch;
  });

  const handleSubmit = async () => {
    setFormError('');
    if (form.honeypot) return; // Silent honeypot reject
    if (!form.title || !form.description || !form.contact || !form.email) {
      setFormError('Title, description, contact and email are required.');
      return;
    }
    if (!form.email.includes('@')) {
      setFormError('Please enter a valid email.');
      return;
    }
    setFormLoading(true);
    try {
      // Save email
      await supabase.from('email_signups').insert([{ email: form.email, source: 'job_submission' }]);
      // Log to activity feed
      await supabase.from('activity_feed').insert([{
        text: `New job posted: "${form.title.substring(0, 50)}" — pending review`,
        icon: '💼',
      }]);
      setSubmitted(true);
      setShowForm(false);
    } catch (e) {
      setFormError('Something went wrong. Please try again.');
      console.error(e);
    } finally {
      setFormLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-zinc-950 text-white">
      <section className="px-6 py-12 max-w-5xl mx-auto">

        <div className="flex items-start justify-between mb-8 gap-4 flex-wrap">
          <div>
            <h1 className="text-3xl font-bold text-white mb-2">Jobs Board</h1>
            <p className="text-zinc-400">Bots hiring humans. Humans offering services. AI companies you can hire.</p>
          </div>
          <button onClick={() => setShowForm(true)}
            className="bg-orange-500 hover:bg-orange-400 text-white font-medium px-5 py-2.5 rounded-lg text-sm transition-all shrink-0">
            + Post a Listing
          </button>
        </div>

        {submitted && (
          <div className="bg-emerald-500/10 border border-emerald-500/30 rounded-xl p-4 mb-6 text-emerald-400 text-sm">
            ✓ Your listing has been submitted for review. We'll be in touch shortly.
          </div>
        )}

        {/* TYPE FILTERS */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-6">
          {Object.entries(typeConfig).map(([key, val]) => (
            <button key={key} onClick={() => setActiveType(activeType === key ? "All" : key)}
              className={"p-4 rounded-xl border text-left transition-all " + (
                activeType === key
                  ? val.bg + " " + val.border + " " + val.text
                  : "bg-zinc-900 border-zinc-800 text-zinc-400 hover:border-zinc-600"
              )}>
              <div className="font-medium text-sm mb-1">{val.label}</div>
              <div className="text-xs opacity-70">{DEMO_JOBS.filter(j => j.type === key).length} listings</div>
            </button>
          ))}
        </div>

        <input type="text" placeholder="Search listings..." value={search} onChange={e => setSearch(e.target.value)}
          className="bg-zinc-900 border border-zinc-800 rounded-lg px-4 py-3 text-sm text-white placeholder:text-zinc-600 w-full focus:outline-none focus:border-zinc-600 mb-6" />

        <div className="text-xs text-zinc-600 mb-4">{filtered.length} listings</div>

        <div className="flex flex-col gap-4">
          {filtered.map(job => {
            const config = typeConfig[job.type];
            const shareText = `${typeConfig[job.type].label.replace(/[🤖🙋⚡]/g, '').trim()}\n\n${job.title}\n${job.company}\n\n${job.description.substring(0, 150)}...\n\nRate: ${job.rate}`;
            return (
              <div key={job.id} className="bg-zinc-900 border border-zinc-800 rounded-xl p-6 hover:border-zinc-700 transition-all">
                <div className="flex items-start justify-between gap-4 mb-3 flex-wrap">
                  <div>
                    <h3 className="font-semibold text-white text-lg mb-1">{job.title}</h3>
                    <div className="text-sm text-zinc-500">{job.company}</div>
                  </div>
                  <div className="flex flex-col items-end gap-2 shrink-0">
                    <span className={"text-xs px-3 py-1 rounded-full border " + config.bg + " " + config.text + " " + config.border}>
                      {config.label}
                    </span>
                    <span className="text-xs text-zinc-600">{job.posted}</span>
                  </div>
                </div>
                <p className="text-sm text-zinc-400 leading-relaxed mb-4">{job.description}</p>
                <div className="flex items-center justify-between flex-wrap gap-3">
                  <div className="flex items-center gap-3 flex-wrap">
                    <span className="text-sm font-medium text-emerald-400">{job.rate}</span>
                    <span className="text-xs text-zinc-600 bg-zinc-800 px-2 py-1 rounded">{job.category}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <ShareButton
                      title={job.title}
                      text={shareText}
                      url="https://wtfagents.com/jobs"
                      label="📤 Share"
                    />
                    <a href={"mailto:" + job.contact}
                      className="text-sm bg-zinc-800 hover:bg-zinc-700 text-zinc-300 hover:text-white px-4 py-2 rounded-lg transition-all border border-zinc-700">
                      Apply →
                    </a>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {filtered.length === 0 && (
          <div className="text-center py-16 text-zinc-600">
            <div className="text-4xl mb-3">💼</div>
            <div className="text-sm">No listings found. Be the first to post one.</div>
          </div>
        )}

      </section>

      {/* POST LISTING MODAL */}
      {showForm && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4"
          onClick={e => e.target === e.currentTarget && setShowForm(false)}>
          <div className="bg-zinc-900 border border-zinc-700 rounded-2xl p-6 w-full max-w-lg max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-lg font-bold">Post a Listing</h2>
              <button onClick={() => setShowForm(false)} className="text-zinc-500 hover:text-white text-xl">✕</button>
            </div>

            {/* HONEYPOT */}
            <input type="text" name="website" value={form.honeypot}
              onChange={e => setForm(f => ({ ...f, honeypot: e.target.value }))}
              style={{ display: 'none' }} tabIndex={-1} autoComplete="off" />

            <div className="flex flex-col gap-4">
              <div>
                <label className="text-xs text-zinc-500 mb-1.5 block">Listing Type</label>
                <select value={form.type} onChange={e => setForm(f => ({ ...f, type: e.target.value }))}
                  className="bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2.5 text-sm text-white w-full focus:outline-none">
                  <option value="ai_hiring_human">🤖 Bot / AI Company Hiring a Human</option>
                  <option value="human_offering">🙋 Human Offering Services to AI Companies</option>
                  <option value="ai_offering">⚡ AI Company Offering Services</option>
                </select>
              </div>
              <div>
                <label className="text-xs text-zinc-500 mb-1.5 block">Job Title <span className="text-orange-500">*</span></label>
                <input type="text" placeholder="e.g. Human Sales Closer Needed" value={form.title}
                  onChange={e => setForm(f => ({ ...f, title: e.target.value }))}
                  className="bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2.5 text-sm text-white w-full focus:outline-none placeholder:text-zinc-600" />
              </div>
              <div>
                <label className="text-xs text-zinc-500 mb-1.5 block">Company / Your Name <span className="text-orange-500">*</span></label>
                <input type="text" placeholder="e.g. RoofMax AI or Sarah M." value={form.company}
                  onChange={e => setForm(f => ({ ...f, company: e.target.value }))}
                  className="bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2.5 text-sm text-white w-full focus:outline-none placeholder:text-zinc-600" />
              </div>
              <div>
                <label className="text-xs text-zinc-500 mb-1.5 block">Description <span className="text-orange-500">*</span></label>
                <textarea placeholder="Describe the role, what's needed, and any requirements..." value={form.description}
                  onChange={e => setForm(f => ({ ...f, description: stripLinks(e.target.value) }))} rows={4}
                  className="bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2.5 text-sm text-white w-full focus:outline-none placeholder:text-zinc-600 resize-none" />
              </div>
              <div>
                <label className="text-xs text-zinc-500 mb-1.5 block">Rate / Compensation</label>
                <input type="text" placeholder="e.g. $500/mo, $75/video, Revenue share" value={form.rate}
                  onChange={e => setForm(f => ({ ...f, rate: e.target.value }))}
                  className="bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2.5 text-sm text-white w-full focus:outline-none placeholder:text-zinc-600" />
              </div>
              <div>
                <label className="text-xs text-zinc-500 mb-1.5 block">Contact (email or company URL) <span className="text-orange-500">*</span></label>
                <input type="text" placeholder="you@example.com" value={form.contact}
                  onChange={e => setForm(f => ({ ...f, contact: e.target.value }))}
                  className="bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2.5 text-sm text-white w-full focus:outline-none placeholder:text-zinc-600" />
              </div>
              <div>
                <label className="text-xs text-zinc-500 mb-1.5 block">Your Email <span className="text-orange-500">*</span></label>
                <input type="email" placeholder="For listing updates and notifications" value={form.email}
                  onChange={e => setForm(f => ({ ...f, email: e.target.value }))}
                  className="bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2.5 text-sm text-white w-full focus:outline-none placeholder:text-zinc-600" />
              </div>
              {formError && <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-3 text-red-400 text-sm">{formError}</div>}
              <button onClick={handleSubmit} disabled={formLoading}
                className="bg-orange-500 hover:bg-orange-400 disabled:opacity-50 text-white font-medium px-5 py-3 rounded-lg text-sm transition-all mt-2">
                {formLoading ? "Submitting..." : "Submit Listing — Free"}
              </button>
              <p className="text-xs text-zinc-600 text-center">Listings are reviewed before going live. Free during beta.</p>
            </div>
          </div>
        </div>
      )}

      <footer className="border-t border-zinc-800 px-6 py-6 text-center text-xs text-zinc-600">
        WTF Agents Jobs Board · <a href="/submit" className="text-orange-500 hover:text-orange-400">Submit your AI company</a>
      </footer>
    </div>
  );
}
